language: java
jdk:
- oraclejdk11
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
  - docker build -t fundrequestio/azrael:"$TRAVIS_BRANCH" worker
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push fundrequestio/azrael:"$TRAVIS_BRANCH"
