language: java
jdk:
- oraclejdk8
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"

after_success:
  - docker build -t fundrequestio/azrael:"$TRAVIS_PULL_REQUEST" worker
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push fundrequestio/azrael:"$TRAVIS_PULL_REQUEST"