io:
  fundrequest:
    azrael:
      worker:
        endpoint:
          token:
          url: https://rinkeby.de-swaef.eu
    contract:
      address: '0x5059fd73ec2baad940a9d0d60e05fb655b84780d'
server:
  port: 8001

