io:
  fundrequest:
    azrael:
      queue:
        fund: 'azrael_kovan_fund'
        claim: 'azrael_kovan_claim'
        paid: 'azrael_kovan_paid'
        transfer: 'azrael_kovan_transfer'
        approved-claim: 'approved-claims'
      worker:
        endpoint:
          url: https://kovan.fundrequest.io
      claim:
        gasprice: '1000000000'
        gaslimit: '400000'
    token:
      address: '0x9f88c5cc76148d41a5db8d0a7e581481efc9667b'
    contract:
      address: '0x0ade7b8f58ba034a2a818f1fd48c3c92039c1cc8'
server:
  port: 8001

spring:
  rabbitmq:
    host: localhost
    password: default_pass
    connection-timeout: 60000