io:
  fundrequest:
    azrael:
      username: username
      password: password
      queue:
        fund: 'azrael_kovan_fund'
        claim: 'azrael_kovan_claim'
        refund: 'azrael_kovan_refund'
        paid: 'azrael_kovan_paid'
        transfer: 'azrael_kovan_transfer'
        approved-claim: 'approved-claims'
      worker:
        endpoint:
          url: https://kovan.fundrequest.io
      claim:
        gasprice: '1000000000'
        gaslimit: '2000000'
    contract:
      address: '0x59fcdfbda305f934bc6d982170c31287c4f1f434'
server:
  port: 8001
spring:
  rabbitmq:
    host: localhost
    password: default_pass
    connection-timeout: 60000
management:
  port: 9005
endpoints:
  health:
    sensitive: true
    enabled: true
  enabled: false
logging:
  level:
    io:
      fundrequest:
        azrael:
          worker: debug
